[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#009653"
backgroundColor="#F5F5F5"
secondaryBackgroundColor="#E0E0E0"
textColor="#333333"
font="sans serif"
